#This is the configuration file for DragonPower
#All configuration values work apart from the dragons storage
#A tutorial on how to configure this plugin will come soon

logAPICalls: true
fireDragon:
  flyingEnabled: true
  flyingMultiplier: 4
  fireballEnabled: true
  fireballPhysicsEnabled: true
  fireballMuliplier: 1.5
  fireballExplosionPower: 2
  fireballRadius: 2
  fallDamageReductionEnabled: true
  fallDamageReduction: 0.5
  fireDamagePrevention: true
earthDragon:
  flyingEnabled: true
  flyingMultiplier: 4
  earthPropulsionEnabled: true
  earthPropulsionRadius: 2
  earthPropulsionMultiplier: 1
  earthPropulsionMultiplierRandom: 1
  earthPropulsionTargetLimit: 100
  fallEarthBoomEnabled: true
  fallEarthBoomVelocity: 0.5
  fallDamageReductionEnabled: true
  fallDamageReduction: 0
  earthPunchEnabled: true
  earthPunchRadius: 2
waterDragon:
  flyingEnabled: true
  flyingMultiplier: 4
  waterBlastEnabled: true
  waterBlastDistance: 50
  waterBlastData: 7
dragons:
  SOME_UUID: FIRE
  OTHER_UUID: WATER
  JASONS_UUID: EARTH